#version: '3'
#services:
#    db:
#      image: postgres
#      environment:
#        - POSTGRES_DB=postgres
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=password
#      ports:
#        - "127.0.0.1:5432:5432"
#    api:
#      build: .
#      volumes:
#        - .:/code
#      ports:
#        - "127.0.0.1:8000:8000"
#      env_file:
#        - .env
#      depends_on:
#        - db
version: '3'

services:
  app:
    build: .
#    ports:
#        - "127.0.0.1:8000:80"
    volumes:
    - ./:/project
    env_file: .env
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
    - "127.0.0.1:80:80"
    depends_on:
      - app